# Generated by Django 4.0.1 on 2022-01-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('decription', models.TextField(max_length=250, verbose_name='Описание')),
            ],
        ),
        migrations.AlterModelOptions(
            name='topphone',
            options={'verbose_name': 'Популярный телефон', 'verbose_name_plural': 'Популярные телефоны'},
        ),
    ]
