# Generated by Django 4.0.1 on 2022-01-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_imagecarousel_alter_topphone_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagecarousel',
            old_name='decription',
            new_name='description',
        ),
    ]
