# Generated by Django 4.0.1 on 2022-01-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productcatalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='topphone',
            name='urltoprodust',
            field=models.URLField(default=1, verbose_name='Ссылка к товару'),
            preserve_default=False,
        ),
    ]
