# Generated by Django 4.0.1 on 2022-01-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_topphone_urltoprodust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topphone',
            name='urltoprodust',
            field=models.CharField(default='product', max_length=100, verbose_name='Ссылка к товару'),
        ),
    ]
